--
-- Timbre editor
--

local TONES = {
    A = {"AcouPiano1","AcouPiano2","AcouPiano3","Honky-Tonk","ElecPiano1","ElecPiano2","ElecPiano3","ElecPiano4","ElecOrgan1","ElecOrgan2","ElecOrgan3","ElecOrgan4","PipeOrgan1","PipeOrgan2","PipeOrgan3","Accordion","Harpsi 1","Harpsi 2","Harpsi 3","Clav 1","Clav 2","Clav 3","Celesta 1","Celesta 2","Violin 1","Violin 2","Cello 1","Cello 2","Contrabass","Pizzicato","Harp","Harp 2","Strings 1","Strings 2","Strings 3","Strings 4","Brass 1","Brass 2","Brass 3","Brass 4","Trumpet 1","Trumpet 2","Trombone 1","Trombone 2","Horn","Fr Horn","Engl Horn","Tuba","Flute 1","Flute 2","Piccolo","Recorder","Pan Pipes","Bottleblow","Breathpipe","Whistle","Sax 1","Sax 2","Sax 3","Clarinet 1","Clarinet 2","Oboe","Bassoon","Harmonica"},
    B = {"Fantasy","Harmo Pan","Chorale","Glasses","Soundtrack","Atmosphere","Warm Bell","Space Horn","Echo Bell","Ice Rains","Oboe 2002","Echo Pan","Bell Swing","Reso Synth","Steam Pad","VibeString","Syn Lead 1","Syn Lead 2","Syn Lead 3","Syn Lead 4","Syn Bass 1","Syn Bass 2","Syn Bass 3","Syn Bass 4","AcouBass 1","AcouBass 2","ElecBass 1","ElecBass 2","SlapBass 1","SlapBass 2","Fretless 1","Fretless 2","Vibe","Glock","Marimba","Xylophone","Guitar 1","Guitar 2","Elec Gtr 1","Elec Gtr 2","Koto","Shamisen","Jamisen","Sho","Shakuhachi","WadaikoSet","Sitar","Steel Drum","Tech Snare","Elec Tom","Revrse Cym","Ethno Hit","Timpani","Triangle","Wind Bell","Tube Bell","Orche Hit","Bird Tweet","OneNoteJam","Telephone","Typewriter","Insect","WaterBells","JungleTune"},
    RHYTHM = {"Closed High Hat 1","Closed High Hat 2","Open High Hat 1","Open High Hat 2","Crash Cymbal","Crash Cymbal (short)","Crash Cymbal (mute)","Ride Cymbal","Ride Cymbal (short)","Ride Cymbal (mute)","Cup","Cup (mute)","China Cymbal","Splash Cymbal","Bass Drum 1","Bass Drum 2","Bass Drum 3","Bass Drum 4","Snare Drum 1","Snare Drum 2","Snare Drum 3","Snare Drum 4","Snare Drum 5","Snare Drum 6","Rim Shot","Brush 1","Brush 2","High Tom Tom 1","Middle Tom Tom 1","Low Tom Tom 1","High Tom Tom 2","Middle Tom Tom 2","Low Tom Tom 2","High Tom Tom 3","Middle Tom Tom 3","Low Tom Tom 3","High Pitch Tom Tom 1","High Pitch Tom Tom 2","Hand Clap","Tambourine","Cowbell","High Bongo","Low Bongo","High Conga (mute)","High Conga","Low Conga","High Timbale","Low Timbale","High Agogo","Low Agogo","Cabasa","Maracas","Short Whistle","Long Whistle","Quijada","Claves","Castanets","Triangle","Wood Block","Bell","Native Drum 1","Native Drum 2","Native Drum 3","OFF"}
}

function timbreControls(mod, value)
	console("timbreControls")
end